services:

  proxy:
    build: .
    image: cc7261:pyzmq
    container_name: proxy
    volumes:
      - ./proxy.py:/app/main.py
    ports:
      - "5555:5555"
      - "5556:5556"

  publisher_h:
    build: .
    image: cc7261:pyzmq
    volumes:
      - ./publisher_h.py:/app/main.py
    depends_on:
      - proxy

  publisher_d:
    build: .
    image: cc7261:pyzmq
    volumes:
      - ./publisher_d.py:/app/main.py
    depends_on:
      - proxy

  subscriber_h:
    build: .
    image: cc7261:pyzmq
    volumes:
      - ./subscriber_h.py:/app/main.py
    depends_on:
      - proxy

  subscriber_d:
    build: .
    image: cc7261:pyzmq
    volumes:
      - ./subscriber_d.py:/app/main.py
    depends_on:
      - proxy

  subscriber_todos:
    build: .
    image: cc7261:pyzmq
    volumes:
      - ./subscriber_todos.py:/app/main.py
    depends_on:
      - proxy